### PR TITLE
Fix value auto is set like null

### PR DESCRIPTION
**Pull request by paulomenezes**
When I use the property with 'auto', it set like null, for example:

```css
img {
  width: 100%;
  height: auto;
}
```

Generate:
```css
"img":{"width":100,"height":null}
```

I compare the value, if the value is auto, I don't parse the value.

It's my first pull request, tell me if I can do it better.

Thanks

### CODE REVIEW

**Comment by jpomazal** [comment]
I think the issue is that in React Native, all values that would take percentages or the 'auto' value in standard CSS can only accept pixel units.  Additionally, passing null should result in effectively the 'auto' layout equivalent for height while passing the string 'auto' will throw an error in RN, meaning the 'auto' -> null transform is valid.  Replicating 'auto' values for properties such as margin requires flexbox align and justify properties.

Instead of of passing auto value through or just the truncated numeric for relatives values (%, em, etc.) as well as non-supported values ('calc()' for example), it should probably omit the property in the output entirely and throw a console warning to the user.  A warning mentioning that relative values are not supported and they need to be using flexbox for any non-static layouts would be perfect.

Some validation would be good all around.  Since this is only run at build time, we don't really have to worry about any performance issues with adding the extra layer to the transform process. Since I think one of the major use cases (if not the main use case) of this project is leveraging existing CSS assets or allowing designers to create assets in their native tongue, validation could play a big roll.

Good links to point to in warning messages:
https://facebook.github.io/react-native/docs/layout-props.html
https://facebook.github.io/react-native/docs/flexbox.html

**Comment by paulomenezes** [comment]
Set the value to null and show a warning message?

**Comment by sabeurthabti** [comment]
Agreed to need some validation messages and defiantly something I want to improve. In regards to this PR, we should really avoid setting null values and merge this PR but I will let @jpomazal decide. 

I will set a milestone for us.

**Comment by jpomazal** [comment]
This pull sets the value to 'auto', which will throw an error in RN.  I'll close this and create an issue for validation.

**Pull request closed without merging**
