### PR TITLE
Hotfix on add wrong path to input file

### PR DESCRIPTION
**Pull request by DrMabuse23**
node_modules/react-native-css/build/index.js:266
		return string.replace(/\r?\n|\r/g, "");
		             ^

TypeError: Cannot read property 'replace' of undefined

### CODE REVIEW

**Comment by sabeurthabti** [comment]
thanks for this, I will go ahead and merge it.

**Comment by sabeurthabti** [comment]
https://circleci.com/gh/sabeurthabti/react-native-css/60

new version is react-native-css@1.2.19

**Comment by sabeurthabti** [comment]
hi @DrMabuse23 can you give a little feedback? how are you finding this module. Thanks, any feedback is welcomed.

**Comment by DrMabuse23** [comment]
Hi @sabeurthabi module works great, save me more time. Great is the scss support. What kam missing is a feature like 
`````
-i ./**.*.JS -o ./dist/assets/styles

**Comment by sabeurthabti** [comment]
@DrMabuse23 i think this can be solved via the glob module, I will investigate. thanks

**Pull request merged**
